language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - TYPO3_VERSION="7.6.*"
  - TYPO3_VERSION="8.6.*"
  - TYPO3_VERSION="dev-master"

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION="8.6.*"
    - php: 5.6
      env: TYPO3_VERSION="8.6.*"
    - php: 5.5
      env: TYPO3_VERSION="dev-master"
    - php: 5.6
      env: TYPO3_VERSION="dev-master"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running base build for TYPO3 $TYPO3_VERSION";
